import {
  BUN_TRAILER,
  BUN_VERSION_MATCH,
  BUN_VERSION_MATCH_OLD,
  BUNFS_ROOT,
  BUNFS_ROOT_OLD,
} from "./constants";
import { locateDataSection } from "./formats";
import { findBunSection } from "./macho";
import { parseOffsets } from "./offsets";

export interface BundledFile {
  path: string;
  contents: ArrayBuffer;
  sourcemap?: {
    version: 3;
    file: string;
    debugId?: string;
    mappings: string;
    sources: string[];
  };
}

const corruptionMessage =
  ". Either the binary is corrupted or it's not an executable file generated by `bun build --compile`.";

export class InvalidExecutableError extends Error {
  constructor(msg = "Invalid executable") {
    super(msg + corruptionMessage);
    this.name = "InvalidExecutableError";
  }
}

export class InvalidTrailerError extends InvalidExecutableError {
  constructor() {
    super("Invalid executable trailer");
    this.name = "InvalidTrailerError";
  }
}

export class TotalByteCountMismatchError extends InvalidExecutableError {
  constructor() {
    super("Executable byte count mismatch");
    this.name = "TotalByteCountMismatchError";
  }
}

export class VersionNotFoundError extends InvalidExecutableError {
  constructor() {
    super("Version not found in executable");
    this.name = "VersionNotFoundError";
  }
}

export interface ExtractBundledFilesOptions {
  normaliseEntrypointFileName?: boolean;
}

export function extractBundledFiles(
  compiledBinaryData: DataView | ArrayBuffer,
  options: ExtractBundledFilesOptions = {},
) {
  options = {
    normaliseEntrypointFileName: true,
    ...options,
  };

  if (compiledBinaryData instanceof ArrayBuffer) {
    compiledBinaryData = new DataView(compiledBinaryData);
  }

  const decoder = new TextDecoder();

  // Note: reverse engineering
  // bun/src/StandaloneModuleGraph.zig/StandaloneModuleGraph/toBytes

  // 1. Locate the data section (Mach-O __BUN/__bun or appended to file end)
  const section = locateDataSection(compiledBinaryData);
  if (!section) {
    throw new InvalidTrailerError();
  }

  // 2. Compute trailer offset and validate container-specific invariants
  let dataView: DataView;
  let trailerOffset: number;
  let modulesStart: number;

  if (section.container === "macho") {
    // Mach-O: section.data = [header?][modules][metadata][Offsets][trailer 16B]
    // Different Bun versions have 0, 4, or 8 byte headers; modulesStart is
    // computed after parsing offsets below.
    dataView = section.data;
    trailerOffset = dataView.byteLength - BUN_TRAILER.length;
    modulesStart = 0; // placeholder, computed after parseOffsets
  } else {
    // Appended: full binary = [...native code...][modules][metadata][Offsets 24B][trailer 16B][totalByteCount 8B]
    dataView = section.data;
    trailerOffset = dataView.byteLength - 8 - BUN_TRAILER.length;

    const totalByteCount = dataView.getUint32(dataView.byteLength - 8, true);
    if (dataView.byteLength !== totalByteCount) {
      throw new TotalByteCountMismatchError();
    }

    // modulesStart computed after parsing offsets below
    modulesStart = 0; // placeholder
  }

  // 3. Parse the Offsets struct (variable size: 24 or 32 bytes)
  const offsets = parseOffsets(dataView, trailerOffset);

  // Compute modulesStart from offsetByteCount
  if (section.container === "macho") {
    // [header?][modules+metadata = offsetByteCount][Offsets][trailer 16B]
    modulesStart =
      dataView.byteLength - (offsets.offsetByteCount + offsets.structSize + BUN_TRAILER.length);
  } else {
    // [native code][modules+metadata = offsetByteCount][Offsets][trailer 16B][totalByteCount 8B]
    modulesStart =
      dataView.byteLength - (offsets.offsetByteCount + offsets.structSize + BUN_TRAILER.length + 8);
  }

  // 4. Extract module data
  const modulesEnd = modulesStart + offsets.modulesPtrOffset;
  const modulesData = dataView.buffer.slice(
    dataView.byteOffset + modulesStart,
    dataView.byteOffset + modulesEnd,
  );

  const modulesMetadataStart = modulesEnd;

  // 5. Determine metadata chunk size and format
  // V4 (structSize 32): 52-byte metadata chunks, new format
  // V2/V3 (structSize 24, new format): 28-byte metadata chunks
  // V1 (structSize 24, old format): 32-byte metadata chunks
  let newFormat: boolean;
  let modulesMetadataChunkSize: number;
  if (offsets.structSize === 32) {
    // V4 format: metadata chunks grew to 52 bytes
    newFormat = true;
    modulesMetadataChunkSize = 52;
  } else if (section.container === "macho") {
    // V3: Mach-O with 24-byte offsets, always new format
    newFormat = true;
    modulesMetadataChunkSize = 36;
  } else {
    // V1/V2 appended format: use the existing heuristic
    const structStart = trailerOffset - offsets.structSize;
    const payloadSize =
      dataView.getUint32(structStart - 20, true) + dataView.getUint32(structStart - 16, true);
    newFormat = payloadSize + 1 === offsets.modulesPtrOffset;
    modulesMetadataChunkSize = newFormat ? 28 : 32;
  }

  // 6. Parse each module
  const bundledFiles: BundledFile[] = [];
  let currentOffset = 0;
  for (let i = 0; i < offsets.modulesPtrLength / modulesMetadataChunkSize; i++) {
    const isEntrypoint = i === offsets.entryPointId;

    const modulesMetadataOffset = modulesMetadataStart + i * modulesMetadataChunkSize;
    const pathLength = dataView.getUint32(modulesMetadataOffset + 4, true);
    const contentsLength = dataView.getUint32(modulesMetadataOffset + 12, true);
    const sourcemapLength = dataView.getUint32(modulesMetadataOffset + 20, true);

    let path = decoder.decode(modulesData.slice(currentOffset, currentOffset + pathLength));
    if (options.normaliseEntrypointFileName && isEntrypoint) {
      path = path.replace(/\/[^\/\\]+$/, "/index.js");
    }
    path = removeBunfsRootFromPath(path);
    if (path[0] !== "/") {
      throw new InvalidExecutableError("Invalid path in bundled file in executable");
    }
    path = removeLeadingSlash(path);

    const contentsStart = currentOffset + pathLength + (newFormat ? 1 : 0);
    const contentsEnd = contentsStart + contentsLength;
    const contents = modulesData.slice(contentsStart, contentsEnd);

    let sourcemap: BundledFile["sourcemap"];
    if (sourcemapLength) {
      const sourcemapMappingsLength = dataView.getUint32(
        modulesStart + contentsEnd + 5,
        true,
      );

      if (sourcemapMappingsLength) {
        const sourcemapSourcesCount = dataView.getUint32(
          modulesStart + contentsEnd + 1,
          true,
        );

        const mappingsStart = contentsEnd + 9 + sourcemapSourcesCount * 16;
        const mappingsEnd = mappingsStart + sourcemapMappingsLength;

        const contentsEndData = decoder.decode(contents.slice(contents.byteLength - 49));
        const debugId = contentsEndData.match(/^\/\/# debugId=([a-fA-F0-9-]{12,})$/m)?.[1];
        // RegEx copied from the sourcemaps debug-id spec:
        // https://github.com/tc39/source-map/blob/main/proposals/debug-id.md#appendix-a-self-description-of-source-maps-and-javascript-files

        sourcemap = {
          version: 3,
          file: path,
          debugId,
          mappings: decoder.decode(modulesData.slice(mappingsStart, mappingsEnd)),
          sources: [],
        };

        let sourceStart = mappingsEnd;
        for (let j = 0; j < sourcemapSourcesCount; j++) {
          const sourcemapSourceLength = dataView.getUint32(
            modulesStart + contentsEnd + 13 + j * 8,
            true,
          );

          sourcemap.sources.push(
            decoder.decode(modulesData.slice(sourceStart, sourceStart + sourcemapSourceLength)),
          );

          sourceStart += sourcemapSourceLength;
        }
      }
    }

    const bundledFile: BundledFile = { path, contents, sourcemap };
    if (isEntrypoint) {
      bundledFiles.unshift(bundledFile);
    } else {
      bundledFiles.push(bundledFile);
    }

    currentOffset += pathLength + contentsLength + sourcemapLength + (newFormat ? 2 : 0);
  }

  return bundledFiles;
}

function removeBunfsRootFromPath(path: string) {
  if (path.startsWith(BUNFS_ROOT)) {
    return path.slice(BUNFS_ROOT.length);
  }
  if (path.startsWith(BUNFS_ROOT_OLD)) {
    return path.slice(BUNFS_ROOT_OLD.length);
  }
  throw new Error(`Path does not start with Bun-fs root: ${path}`);
}

export function removeLeadingSlash(path: string) {
  return path.replace(/^\/?(?:\.\/)?/, "");
}

export interface BunVersion {
  version: string;
  revision: string;
  newFormat?: boolean;
}

function getExecutableVersionNew(data: Uint8Array, searchLimit: number): BunVersion {
  const versionIndex = data.findIndex((_, index) => {
    if (index >= searchLimit) {
      return false;
    }

    for (let i = 0; i < BUN_VERSION_MATCH.length; i++) {
      if (data[index + i] !== BUN_VERSION_MATCH.charCodeAt(i)) {
        return false;
      }
    }

    return true;
  });

  if (versionIndex === -1) {
    throw new VersionNotFoundError();
  }

  const versionEndIndex = data.indexOf(27, versionIndex + BUN_VERSION_MATCH.length);

  if (versionEndIndex <= 0) {
    throw new VersionNotFoundError();
  }

  const decoder = new TextDecoder();
  const versionString = decoder.decode(
    data.slice(versionIndex + BUN_VERSION_MATCH.length, versionEndIndex),
  );

  const [, version, revision] = versionString.match(/^(.+) \((.+)\)$/) ?? [];

  if (!version) {
    throw new VersionNotFoundError();
  }

  return {
    version,
    revision,
  };
}

function getExecutableVersionOld(data: Uint8Array, searchLimit: number): BunVersion {
  const versionIndex = data.findIndex((_, index) => {
    if (index >= searchLimit) {
      return false;
    }

    for (let i = 0; i < BUN_VERSION_MATCH_OLD.length; i++) {
      if (data[index + i] !== BUN_VERSION_MATCH_OLD.charCodeAt(i)) {
        return false;
      }
    }

    return true;
  });

  if (versionIndex === -1) {
    throw new VersionNotFoundError();
  }

  const versionEndIndex = data.indexOf(58, versionIndex + BUN_VERSION_MATCH_OLD.length);

  if (versionEndIndex <= 0) {
    throw new VersionNotFoundError();
  }

  const decoder = new TextDecoder();
  const versionString = decoder.decode(
    data.slice(versionIndex + BUN_VERSION_MATCH_OLD.length, versionEndIndex),
  );

  const [, version, revision] = versionString.match(/^(.+) \((.+)\)/) ?? [];

  if (!version) {
    throw new VersionNotFoundError();
  }

  return {
    version,
    revision,
  };
}

export function getExecutableVersion(data: Uint8Array | ArrayBuffer): BunVersion {
  if (data instanceof ArrayBuffer) {
    data = new Uint8Array(data);
  }

  const binary = new DataView(data.buffer, data.byteOffset, data.byteLength);

  // Determine search limit to exclude embedded module data
  // (prevents matching fake version strings inside bundled files)
  let searchLimit: number;
  const machoSection = findBunSection(binary);
  if (machoSection) {
    // Don't search inside the __BUN section
    searchLimit = machoSection.offset;
  } else {
    // Legacy appended format: don't search past modules start
    searchLimit = getModulesStartLegacy(binary);
  }

  try {
    return { ...getExecutableVersionNew(data, searchLimit), newFormat: true };
  } catch (e) {
    if (e instanceof VersionNotFoundError) {
      return { ...getExecutableVersionOld(data, searchLimit), newFormat: false };
    }

    throw e;
  }
}

/**
 * Legacy modulesStart calculation for appended format binaries.
 * Used only by getExecutableVersion to determine search bounds.
 */
function getModulesStartLegacy(compiledBinaryData: DataView) {
  if (compiledBinaryData.byteLength <= 48) {
    return compiledBinaryData.byteLength;
  }

  const offsetByteCount = compiledBinaryData.getUint32(compiledBinaryData.byteLength - 48, true);

  return compiledBinaryData.byteLength - (offsetByteCount + 48);
}
